version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: DatabaseBackend/Dockerfile
    image: backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default

  frontend:
    build:
        context: .
        dockerfile: frontend/Dockerfile
    image: "frontend:latest"
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on: 
      - backend