version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: DatabaseBackend/Dockerfile  # Path to your Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: examdb
    ports:
      - "5432:5432"
